---

- hosts: all
  become: true
  tasks:

  - name: Update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
  
  - name: install apache package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"
